### ISSUE TITLE
Cannot helix deploy the project

### ISSUE THREAD

**Issue by kptdobe** [adobe/project-helix.io#56] opened 2019-06-09 07:50 UTC
Just run `hlx deploy` in the project (after decrypting and sourcing the env file) - you get error the following error:

```
[==================================================] analyzing html.js 0.0s
[==================================================] packaging zwitch 0.0s✅  packaging completed
[====================------------------------------] deploying summary_html.js 0.0sPUT https://adobeioruntime.net/api/v1/namespaces/helix/packages/helix-services?overwrite=true Returned HTTP 409 (Conflict) --> "Resource is a package and cannot be converted into a binding."
warn: None of the strains contains package information. Aborting command.
```

@tripodsan feedback: use `hlx deploy --static=build` instead.

I think `hlx deploy` should work with any extra magic property.

**Comment by tripodsan** [comment] 2019-06-09 11:56
@kptdobe the problem is, that you are trying to deploy to the `helix` namespace, which already has different use case for the `helix-services` package. we should not use it to deploy any projects anymore. probably better to use the `helix-clients` namespace, or request a new one, like `helix-projects` or `helix-pages`.

@trieloff WDYT?

**Comment by trieloff** [comment] 2019-06-11 10:48
Yes, we should not use the `helix` workspace for customer stuff, not even our own customer stuff.

**Comment by tripodsan** [comment] 2019-06-12 07:59
fixed by using helix-pages

**Closed by tripodsan** 2019-06-12 07:59 UTC
Labels: bug, docmeplz
